name: Issues Deadline Reminders

on:
  schedule:
    # 15:00 UTC corresponds to 8:00 AM Pacific Daylight Time (PDT)
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  check-deadlines:
    runs-on: ubuntu-latest
    steps:
      - name: Scan Project for Deadlines Due Today
        uses: petrandr/duedate_reminders@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          project_number: 18  
          duedate_field_name: "Deadline" 
          notify_for: "expiring_issues"

      - name: Scan Project for Upcoming Deadlines (3 Days)
        uses: petrandr/duedate_reminders@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          project_number: 18  
          duedate_field_name: "Deadline" 
          notify_for: "upcoming_issues"
